#!/usr/bin/env bash
# Read-only Tutti daemon/reboot monitor.
# It never restarts Tutti, touches CUDA, or submits NVMe I/O.

set -u

INTERVAL_S="${TUTTI_MONITOR_INTERVAL_S:-5}"
LOG_DIR="${TUTTI_MONITOR_LOG_DIR:-/data/home/ryeqiu/tutti-daemon-watch}"
DAEMON_NAME="${TUTTI_DAEMON_NAME:-tutti_daemon}"
PORT="${TUTTI_DAEMON_PORT:-50051}"
STATE_FILE="${LOG_DIR}/state"
LOG_FILE="${LOG_DIR}/events.log"
SNAP_DIR="${LOG_DIR}/snapshots"

mkdir -p "${LOG_DIR}" "${SNAP_DIR}" || exit 1
umask 077

if command -v flock >/dev/null 2>&1; then
    exec 9>"${LOG_DIR}/lock"
    flock -n 9 || exit 0
fi

now() { date --iso-8601=seconds 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z'; }
boot_id() { cat /proc/sys/kernel/random/boot_id 2>/dev/null || printf 'unknown'; }
uptime_s() { awk '{print $1}' /proc/uptime 2>/dev/null || printf 'unknown'; }

kernel_relevant() {
    if command -v journalctl >/dev/null 2>&1; then
        journalctl -k -b 0 --no-pager -n 80 2>/dev/null | \
            grep -Ei 'Unknown ioctl|NVRM|Xid|NVMe|nvme|AER|PCIe|I/O error|reset|watchdog|oom|panic|oops|power key|shutdown' || true
    else
        dmesg --time-format iso 2>/dev/null | tail -n 80 | \
            grep -Ei 'Unknown ioctl|NVRM|Xid|NVMe|nvme|AER|PCIe|I/O error|reset|watchdog|oom|panic|oops|power key|shutdown' || true
    fi
}

log() {
    printf '%s %s\n' "$(now)" "$*" >>"${LOG_FILE}"
}

daemon_pids() {
    pgrep -x "${DAEMON_NAME}" 2>/dev/null | sort -n | paste -sd, - || true
}

write_snapshot() {
    local tag="$1"
    local stamp
    stamp="$(date '+%Y%m%d-%H%M%S')"
    local out="${SNAP_DIR}/${stamp}-${tag}.txt"
    {
        printf 'wall_time=%s\nboot_id=%s\nuptime_s=%s\ndaemon_name=%s\nport=%s\n' \
            "$(now)" "$(boot_id)" "$(uptime_s)" "${DAEMON_NAME}" "${PORT}"
        printf '\n[daemon_ps]\n'
        pgrep -a -x "${DAEMON_NAME}" 2>/dev/null || true
        printf '\n[daemon_proc]\n'
        for pid in $(pgrep -x "${DAEMON_NAME}" 2>/dev/null || true); do
            if [ -r "/proc/${pid}/status" ]; then
                sed -n '1,8p' "/proc/${pid}/status"
                printf 'cmdline='; tr '\0' ' ' <"/proc/${pid}/cmdline" 2>/dev/null || true; printf '\n'
                printf 'fd_count='; find "/proc/${pid}/fd" -maxdepth 1 -type l 2>/dev/null | wc -l
            fi
        done
        printf '\n[port]\n'
        ss -ltnp 2>/dev/null | grep -E ":${PORT}([[:space:]]|$)" || true
        printf '\n[daemon_log_tail]\n'
        tail -n 80 /data/home/ryeqiu/tutti_daemon.log 2>/dev/null || true
        printf '\n[gpu]\n'
        if command -v nvidia-smi >/dev/null 2>&1; then
            nvidia-smi --query-gpu=index,utilization.gpu,memory.used,temperature.gpu,power.draw \
                --format=csv,noheader,nounits 2>&1 || true
        else
            printf 'nvidia-smi=unavailable\n'
        fi
        printf '\n[nvme_sysfs]\n'
        for path in /sys/block/nvme*/device/state /sys/class/nvme/nvme*/state; do
            [ -r "${path}" ] && printf '%s=' "${path}" && cat "${path}"
        done
        printf '\n[kernel_relevant]\n'
        kernel_relevant
    } >"${out}" 2>&1
    printf '%s\n' "${out}"
}

previous_boot=""
previous_daemon=""
previous_port=""
previous_kernel_hash=""
if [ -r "${STATE_FILE}" ]; then
    # state is generated by this script, but keep parsing deliberately narrow.
    previous_boot="$(sed -n 's/^boot_id=//p' "${STATE_FILE}" | head -1)"
    previous_daemon="$(sed -n 's/^daemon=//p' "${STATE_FILE}" | head -1)"
    previous_port="$(sed -n 's/^port=//p' "${STATE_FILE}" | head -1)"
    previous_kernel_hash="$(sed -n 's/^kernel_hash=//p' "${STATE_FILE}" | head -1)"
fi

current_boot="$(boot_id)"
if [ -n "${previous_boot}" ] && [ "${previous_boot}" != "${current_boot}" ]; then
    log "BOOT_CHANGE previous=${previous_boot} current=${current_boot} uptime_s=$(uptime_s)"
    write_snapshot "boot-change" >/dev/null
elif [ -z "${previous_boot}" ]; then
    log "MONITOR_START boot=${current_boot} uptime_s=$(uptime_s)"
    write_snapshot "start" >/dev/null
fi

stopped=0
on_stop() {
    [ "${stopped}" -eq 1 ] && return 0
    stopped=1
    log "MONITOR_STOP boot=$(boot_id) uptime_s=$(uptime_s)"
}
trap 'on_stop; exit 0' INT TERM
trap 'on_stop' EXIT

while :; do
    current_boot="$(boot_id)"
    current_daemon="$(daemon_pids)"
    current_port="$(ss -ltnp 2>/dev/null | grep -E ":${PORT}([[:space:]]|$)" | tr -s " " | cut -d" " -f4- || true)"
    if [ "${current_daemon}" != "${previous_daemon}" ]; then
        log "DAEMON_CHANGE old=${previous_daemon:-none} new=${current_daemon:-none}"
        write_snapshot "daemon-change" >/dev/null
        previous_daemon="${current_daemon}"
    fi
    if [ "${current_port}" != "${previous_port}" ]; then
        log "PORT_CHANGE old=${previous_port:-none} new=${current_port:-none}"
        write_snapshot "port-change" >/dev/null
        previous_port="${current_port}"
    fi
    kernel_hash="$(kernel_relevant | sha256sum | awk '{print $1}')"
    if [ -n "${previous_kernel_hash}" ] &&
       [ "${kernel_hash}" != "${previous_kernel_hash}" ]; then
        log "KERNEL_CHANGE old=${previous_kernel_hash} new=${kernel_hash}"
        write_snapshot "kernel-change" >/dev/null
    fi
    previous_kernel_hash="${kernel_hash}"
    if [ "${current_boot}" != "$(boot_id)" ]; then
        log "BOOT_ID_RACE observed=${current_boot} reread=$(boot_id)"
    fi
    printf 'boot_id=%s\ndaemon=%s\nport=%s\nkernel_hash=%s\n' \
        "${current_boot}" "${previous_daemon}" "${previous_port}" \
        "${previous_kernel_hash}" >"${STATE_FILE}"
    sleep "${INTERVAL_S}"
done
